project_id = "oapxhmkrtpisijtlobcq"

[functions.sync-shopify]
verify_jwt = false

[functions.parse-specs]
verify_jwt = false

[functions.bling-auth]
verify_jwt = false

[functions.bling-api]
verify_jwt = false

[functions.calcular-frete]
verify_jwt = false

[functions.sync-shopify-orders]
verify_jwt = false

[functions.read-pedidos-lancar]
verify_jwt = false
